import { NlpManager } from "node-nlp";

export function addDeleteIntent(manager: NlpManager): void {
  const deleteDocs = [
    // Core product deletes (essential for distinguishing from save)
    "delete pepper",
    "delete rice",
    "delete garri",
    "delete coke",
    "delete tomato",
    "delete beans",
    "delete yam",
    "delete fuel",
    "delete palm oil",
    "delete sugar",
    "delete water",
    "delete bread",
    "delete milk",
    "delete egg",
    "delete chicken",
    "delete onion",
    "delete indomie",
    "delete diesel",
    "delete petrol",
    "delete flour",
    "delete salt",
    "delete data",
    "delete airtime",
    "delete bag",
    "delete shoe",
    "delete shirt",
    "delete phone",
    "delete laptop",
    "delete charger",
    "delete generator",
    "remove pepper",
    "remove rice",
    "remove garri",
    "remove coke",
    "remove tomato",
    "remove beans",
    "remove yam",
    "remove fuel",
    "clear pepper",
    "clear rice",
    "clear garri",
    "clear coke",
    "erase pepper",
    "erase rice",

    // Contact deletes
    "delete john",
    "delete mike",
    "delete emeka",
    "delete chioma",
    "delete bola",
    "delete tunde",
    "remove john",
    "remove mike",
    "remove emeka",
    "delete my contact john",
    "remove john from my contacts",
    "delete that contact",
    "remove saved contact",
    "erase contact",
    "clear contact",

    // Note deletes
    "delete my number",
    "delete my password",
    "delete that note",
    "delete my classmate john",
    "remove my number",
    "remove my saved note",
    "remove that password",
    "clear my number",
    "clear my notes",
    "erase my number",
    "erase my password",
    "i want to delete my note",
    "please remove this",
    "delete my saved notes",
    "wipe my notes",
    "erase my saved info",
    "clear all my saved data",

    // Price deletes
    "delete price of coke",
    "delete coke price",
    "delete pepper price",
    "delete rice price",
    "delete garri price",
    "delete tomato price",
    "remove saved price of garri",
    "remove the coke price",
    "remove garri price",
    "remove rice price",
    "remove pepper price",
    "delete that price",
    "clear price of rice",
    "erase the price i saved",
    "delete my saved prices",
    "delete price of bag",
    "remove shoe price",
    "delete the dollar price of milk",
    "remove my gbp price for bread",
    "clear saved usd prices",
    "delete price of coffee in dollars",
    "remove price of rent in pounds",
    "delete all my prices",
    "clear all prices",
    "wipe all prices",

    // File deletes
    "delete image",
    "remove my photo",
    "delete that file",
    "remove my document",
    "delete uploaded file",
    "erase that image",
    "remove my receipt",
    "clear my files",
    "delete all my images",
    "remove all my photos",
    "delete all my documents",

    // Bulk deletes
    "delete all my notes",
    "delete everything",
    "clear everything",
    "wipe all my data",
    "remove all my saved info",
    "delete my uk contact",
    "remove india contact",
    "erase my saved us number",
  ];

  deleteDocs.forEach((doc) => {
    manager.addDocument("en", doc, "delete");
  });

  // Add response examples for better training
  manager.addAnswer("en", "delete", "I'll delete that for you.");
  manager.addAnswer("en", "delete", "Removed from your saved data.");
  manager.addAnswer("en", "delete", "Deleted successfully.");
}