import { NlpManager } from "node-nlp";

export function addRetrieveFilesIntent(manager: NlpManager): void {
  const retrieveFileDocs = [
    "show my images",
    "find my photos",
    "show my pictures",
    "get my uploaded images",
    "find my uploaded photos",
    "show me my images",
    "retrieve my photos",
    "find my screenshots",
    "show my uploaded pictures",
    "do i have any images",
    "show me photos i uploaded",
    "find my scanned images",
    "show image of receipt",
    "find photo of invoice",
    "show my saved images",
    "get my photos",
    "show my profile picture",
    "find my product photos",
    "show my property images",
    "find photo i saved",
    "get my uploaded screenshots",
    "show me my snapshots",
    "find my saved pics",
    "show my business photos",
    "find my id card photo",
    "show photo of my document",
    "show my documents",
    "find my files",
    "show my pdfs",
    "get my uploaded files",
    "find my receipts",
    "show my invoices",
    "retrieve my documents",
    "find my contracts",
    "show my uploaded documents",
    "do i have any files",
    "find my saved documents",
    "get my pdf files",
    "show me files i uploaded",
    "find my reports",
    "show my docs",
    "get all my files",
    "find my tax documents",
    "show my insurance documents",
    "find my tenancy agreement",
    "show my payslip",
    "find my medical records",
    "show my birth certificate",
    "find my passport copy",
    "show my utility bills",
    "find my bank statements",
    "show my school certificate",
    "find my waec result",
    "show my jamb result",
    "find my work permit",
    "show my visa documents",
    "find my business registration",
    "show my cac documents",
    "find my nin slip",
    "show my bvn document",
    "find my land documents",
  ];

  retrieveFileDocs.forEach(doc => manager.addDocument("en", doc, "intent.retrieve"));
}