import { NlpManager } from "node-nlp";

export function addRetrieveIntent(manager: NlpManager): void {
  const retrieveDocs = [
    // Core retrieval patterns
    "find my number",
    "find my password",
    "find john",
    "find my classmate john",
    "find that note about rent",
    "find my email",
    "show my number",
    "show my password",
    "show me my saved notes",
    "show my classmate",
    "show all my contacts",
    "show my bank details",
    "get my number",
    "get my password",
    "get my saved info",
    "retrieve my number",
    "retrieve my notes",
    "search for john",
    "search my notes",
    "look up my number",
    "look up john",
    "what is my password",
    "what is my pin",
    "what is my number",
    "what was my email",
    "what did i save about john",
    "what did i save about rent",
    "do i have any notes",
    "do i have johns number",
    "give me my saved data",
    "check my saved notes",
    "where is my password",
    "i need my number",
    "can you find my classmate",
    "show me what i saved",
    "what did i store",
    "what have i saved",
    "pull up my notes",
    "bring up my saved info",
    "show my recent notes",
    "what notes do i have",
    "find my recent saves",
    "show my saved contacts",
    "find my colleague details",
    "what did i save about mike",
    "find mike number",
    "what is john phone number",
    "show me peter contact",
    "do i have emeka number",
    "find tunde details",
    "search for my customer number",
    "find chioma number",
    "what is chukwu phone number",
    "show me emeka contact",
    "find bola number",
    "get ade number",
    "do i have seun contact",
    "find kunle details",
    "look up ngozi number",
    "show me femi saved info",
    "what is kemi number",
    "find taiwo contact",
    "show me biodun number",
    "get chidi contact",
    "find ifeanyi phone number",
    // Representative international examples (reduced)
    "find james london number",
    "what is oliver uk number",
    "show me emily contact london",
    "find harry phone number uk",
    "get sophie number from london",
    "do i have liam uk contact",
    "find charlotte number england",
    "look up william contact",
    "show me george saved number",
    "what is noah uk phone",
    "find michael us number",
    "what is jessica american number",
    "show me david contact usa",
    "find ashley phone number america",
    "get joshua number united states",
    "do i have tyler us contact",
    "find brittany number",
    "look up christopher contact",
    "show me madison saved info",
    "what is brandon us phone",
    // Representative international examples (reduced)
    "find raj number",
    "what is priya contact",
    "show me arjun phone number",
    "find deepa india contact",
    "get ravi saved number",
    "do i have anjali contact",
    "find amit phone",
    "look up sunita number",
    "show me rohit contact",
    "what is neha saved number",
    // Additional patterns
    "find my account number",
    "show my sort code",
    "what is my routing number",
    "find my iban",
    "show my swift code",
    "what is my social security number",
    "find my national insurance number",
    "show my drivers license number",
    "what is my passport number",
  ];

  retrieveDocs.forEach((doc) => {
    manager.addDocument("en", doc, "retrieve");
  });

  // Add response examples for better training
  manager.addAnswer("en", "retrieve", "I'll help you find that information.");
  manager.addAnswer("en", "retrieve", "Let me search for your saved data.");
  manager.addAnswer("en", "retrieve", "Searching your notes...");
}